[package]
name = "jugaad-cli"
description = "Command line interface for jugaad-rs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[[bin]]
name = "jugaad"
path = "src/main.rs"

[dependencies]
jugaad-core = { path = "../jugaad-core" }
tokio = { workspace = true }
clap = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
